### ISSUE TITLE
doesnt work gives this error message installing packages

### ISSUE THREAD

**Issue by watisdatikalikffffali** [Udxr/Discord-Account-Destroyer#1]
![image](https://user-images.githubusercontent.com/65788718/118140169-1d3f6800-b3d6-11eb-9c8c-3e1fbfb6e0d3.png)

**Comment by Udxr** [comment]
Thank you, I have uploaded a new file which should make sure that you don't get this error again. Please re-download the files again and follow the steps like normal. Let me know if there are any more problems.
